### ISSUE TITLE
Get Value from Dictionary (valueFor) does not compile properly when magic variable is the same as the key

### ISSUE THREAD

**Issue by supermamon** [ActuallyZach/Jellycuts-Issues#101]
## Describe the bug
When using `valueFor` and assigning the result to a magic variable which is the same name as the key, it doesn't compile correctly.

## To Reproduce
Take this code and compile
```
import Shortcuts 1092.6
#Color: red, #Icon: shortcuts
dictionary({"key1": "value1", "key2":"value2"}) >> prefs
valueFor(key: "key1", dictionary: prefs ) >> key1
```

## Expected behavior
A shortcut with 2 actions, Dictionary and Get Value from Dictionary getting the value for `key1`

### Screenshots
![valueFor-Issue](https://user-images.githubusercontent.com/6381508/134933056-3c7c4959-153f-4ae1-a12b-7f040af22dc3.png)

## Information
 - Device: iPhone X
 - OS: IOS 15
 - Jellycuts Version: 1.2(1)
 - Jailbroken? No

**Comment by ActuallyTaylor** [comment]
This has been fixed in version 1.2.1. Thank you for reporting it!
