### ISSUE TITLE
if (variable == nil) { ... } won't compile

### ISSUE THREAD

**Issue by supermamon** [ActuallyZach/Jellycuts-Issues#102]
## Describe the bug
if (variable == nil) { ... } won't compile. It results in a compilation error saying:

`Compilation: Cannot find the variable nil in the scope.`

## To Reproduce
Take this code and and tap the hammer button. 
```
import Shortcuts
#Color: red, #Icon: shortcuts

if (Shortcut Input == nil) {
  alert(alert: "No Value", title: "", cancel: false)
}
```
It will show a message saying **Error: Check Console**
The console will have a message as indicated above.

## Expected behavior
Should not result in an error.

### Screenshots
![if-nil-bug](https://user-images.githubusercontent.com/6381508/134935034-0714b7dd-ef08-479b-a5d6-cc30305cb465.jpeg)

## Information
 - Device: iPhone X
 - OS: IOS 15
 - Jellycuts Version: 1.2(1)
 - Jailbroken? No

**Comment by ActuallyTaylor** [comment]
This has been fixed for v 1.2.1. Thank you for reporting!
