### ISSUE TITLE
Unable to get shortcuts action is.workflow.actions.setvariable

### ISSUE THREAD

**Issue by ghost** [ActuallyZach/Jellycuts-Issues#103]
In my shortcut that I just converted, I recieved a comment containing "Unable to get shortcuts action is.workflow.actions.setvariable" on where the set variable action is supposed to be.

**Comment by ActuallyTaylor** [comment]
Can you please send the link to the shortcut you are trying to convert?

**Comment by ActuallyTaylor** [comment]
Fixed in version 1.4
