### ISSUE TITLE
Cannot sign during export

### ISSUE THREAD

**Issue by stevelw** [ActuallyZach/Jellycuts-Issues#104]
Just started using on iOS. 

I cannot export any shortcuts from JC to SC, including the sample ones. 

Error is an HTML string with no details except that signing failed. 

```
Failed To Sign
<!DOCTYPE html>
<html>
<head>
‹meta name="viewport"
content="width=device-width, initial-
scale=1">
«meta charset="utf-8">
<title>Application
Error</title>
<style media="screen">
html, body, iframe {
margin: 0;
padding: 0;
7
html, body {
height: 100%;
overflow: hidden;
7
frame {
width: 100%;
height: 100%;
border: 0;
7
</style>
</head>
<body>
<frame src="I/
www.herokucdn.com/error-pages/
application-error.html"></iframe>
</body>
</html>
Please try again.
```

iOS 15.1; Jellycuts 1.2.1

**Comment by ActuallyTaylor** [comment]
There is currently an issue with the signing sever. Sorry for the inconvenience, I am working to get this fixed ASAP

**Comment by ActuallyTaylor** [comment]
Alright, this should be fixed 👍. Let me know if it is working for you!

**Comment by stevelw** [comment]
Yep, working now.
