### ISSUE TITLE
Notification/Alert content not found

### ISSUE THREAD

**Issue by MrPlayerYork** [ActuallyZach/Jellycuts-Issues#105]
## Describe the bug
I'm trying to use the notifications for debugging, but when I go to compile the script I get '_Compilation Warning: Could not find any content for the parameter cancel in alert_'. When I export it anyway, it looks like it combines the title and cancel/sound parameters into the title space.

## To Reproduce
 1. Make a new Jelly.
 2. Make an alert or notification.
 3. Fill them out as you would normally.
 4. Export to shortcuts.
 5. In shortcuts, look at the title in the drop down off the action.

## Expected behavior
The title to have just what's in the quotations and the boolean to work as expected.

## Information
 - Device: iPhone XR
 - OS: iOS 14.8.1
 - Jellycuts Version 1.3.1(7)
 - Jailbroken? No

**Comment by ActuallyTaylor** [comment]
Can you please send the Jelly code that is causing this issue?

**Comment by MrPlayerYork** [comment]
```
import Shortcuts
#Color: red, #Icon: shortcuts

//check if shortcut input has a value.
var input = Shortcut Input
if(input != nil){
	text(text: "true")
} else {
	text(text: "false")
} >> TestInput

alert(alert: TestInput, title: "debug", cancel: false)
```

**Comment by ActuallyTaylor** [comment]
Thank you! I will get this fixed up for the next version

**Comment by MrPlayerYork** [comment]
I have done multiple different variations of what I'm putting in the parameters, i found that putting no special characters makes it work semi correctly. Semi meaning, i made the magic variable for the if statement and the alert is not linking up.

When I import a shortcut with the expected output, it shows exactly what I typed in here. But when i don't touch it and export right back to shortcuts, its very broken.

So I don't know if I'm doing something wrong.

**Comment by ActuallyTaylor** [comment]
Alright I fixed this up for the next version! You were not doing anything wrong, it was a parser issue on my end. If you would like I can add you to the TestFlight beta for the version. Just fill out [this form](https://forms.gle/ejR1AgGVCnANoBbo6) to get registered for the beta.

[https://forms.gle/ejR1AgGVCnANoBbo6](https://forms.gle/ejR1AgGVCnANoBbo6)
