### ISSUE TITLE
Metdata bug on import

### ISSUE THREAD

**Issue by pac2000** [ActuallyZach/Jellycuts-Issues#116]
OMFG - I love your app and have already paid, will probably being paying more soon. You need to be rewarded!!

## Describe the bug

When I import an existing shortcut to Jelly, I always get this error when I try to compile
"complilation error: blue#icon does not exist ...."

The imported code is:
`#Color blue,#Icon shortcuts`

editing the code to put a space after "blue," fixes the bug
`#Color blue,  #Icon shortcuts`

AS bugs goes, this is innocuous, quick to fix, but it's a bit annoy having to do it every time.

## Information
 - Device: iPad pro 11" 3rd gen
 - OS: iOS 15.5
 - Jellycuts Version v1.3.3(0)
 - Jailbroken? No

**Comment by ActuallyTaylor** [comment]
Thank you so much! That means a ton to me. 

I have checked out this issue on the importer and fixed it for the next version!
