### ISSUE TITLE
Unable to export shortcut in Jellycuts back to Shortcuts

### ISSUE THREAD

**Issue by ghost** [ActuallyZach/Jellycuts-Issues#120]
# What action is the issue?
What action is not correctly translating? [e.g. Send Notification]

## Describe the bug
Unable to export a previously uploaded Shortcut in iCloud within Jellycut, back to the Shortcuts app, because of an upload issue.

## Steps To Reproduce
I imported a Shortcut to jellycut with the Import iCloud Link feature. 
I changes something in the code
I then want to export it back to Shortcuts
The signing process finishes but then I get the error message, that I have to upload the Shortcut first to iCloud.

## Information
 - Device: iPad Pro
 - OS: iOS 16.1
 - Jellycuts Version 1.4

**Comment by ghost** [comment]
Found the issue. Issue is related to Jellycuts helper Shortcut. Latest version is from before iOS/iPadOS 16. So I changed in the shortcut every action  "If [System Version] [does not contain] [15]" with "If [System Version] [does not contain] [16]"

Now it is working.

**Comment by ActuallyTaylor** [comment]
I'm happy you managed to find the fix. I just pushed a version of the helper. It should auto update in the app the next time you export a Jellycut.
