### ISSUE TITLE
Signing Error

### ISSUE THREAD

**Issue by lublak** [ActuallyZach/Jellycuts-Issues#125]
## Describe the bug

If i try to export an example ap i get.a signing error.

## To Reproduce
1. Export an example

## Expected behavior
Add rhe code as an shortcut to the shortcut app

### Screenshots

<img width="1366" alt="Bildschirmfoto 2023-01-19 um 23 56 29" src="https://user-images.githubusercontent.com/44057030/213580751-48485f8d-15a1-42bb-8c7a-5a8fdc511f2a.png">

## Information
 - Device: IPad Pro M2 
 - OS: IPad Os 16.2
 - Jellycuts Version 1.4.1(5)
 - Jailbroken? No

**Comment by ActuallyTaylor** [comment]
I am restarting the servers to fix this issue. Should be fixed within the hour

**Comment by ActuallyTaylor** [comment]
Okay server is restarted. Please try exporting again

**Comment by lublak** [comment]
@ActuallyZach yes it works :)
Now my question is: So the app does not work without internet connection? Is the signing even necessary? And if so, can it be done offline?

**Comment by ActuallyTaylor** [comment]
> @ActuallyZach yes it works :)
> 
> Now my question is: So the app does not work without internet connection? Is the signing even necessary? And if so, can it be done offline?

It does need an internet connection. After iOS 15 the signing is an absolutely necessary step in the process. Apple no longer allows importing of unsigned shortcuts. The only known way to sign shortcuts currently is using a macOS Server to do so.
