### ISSUE TITLE
Failed to sign shortcuts

### ISSUE THREAD

**Issue by amsyeung** [ActuallyZach/Jellycuts-Issues#130]
# What action is the issue?
Failed to sign shortcuts

## Describe the bug
title: Failed To Sign
message: Failed to sign shortcuts - Shortcuts Command Line Unity failed. Please try again.

## Information
 - Device: iPhone 12 mini
 - OS: iOS 16.5
 - Jellycuts v1.4.1(5)

**Comment by ActuallyTaylor** [comment]
I will check this put asap! It looks like something failed with the server's disk. I will get this resolved

**Comment by ActuallyTaylor** [comment]
Okay so I was partially correct. Something is wrong with on the iCloud side of the signing server. Seems like the utility is not working at all right now.

**Comment by amsyeung** [comment]
Seems the server works again now. Thanks for your support.
