### ISSUE TITLE
Failed to sign - malformed data, please try again

### ISSUE THREAD

**Issue by Misaka-0x447f** [ActuallyZach/Jellycuts-Issues#135]
## Describe the bug
Jellycuts always saying "Failed to sign" when trying to to export. How can I help to debug?

## To Reproduce
1. Install the app and setup
2. Install helper
3. Click any of shortcut file and try to export
4. Jellycut prompts "an update is available (screenshot 1)
5. Update the helper as guided
6. Try to export again, then failed to sign (screenshot 2)

## Expected behavior
Signing normally.

### Screenshots
![image](https://github.com/ActuallyTaylor/Jellycuts-Issues/assets/15797507/e5140acb-3509-4fd1-986e-b3d16d5cd75f)
![image](https://github.com/ActuallyTaylor/Jellycuts-Issues/assets/15797507/5299068c-e807-4e5f-8ac4-64fcc4fd729a)

## Information
 - Device: iPhone SE 3
 - OS: iOS 17.0.3
 - Jellycuts Version: 1.4.1(5)
 - Jailbroken? No

**Comment by ActuallyTaylor** [comment]
I just restarted the server see if it’s working now!

**Comment by Misaka-0x447f** [comment]
> I just restarted the server see if it’s working now!

Unfortunately, no. Also, I updated OS to 17.1(21B74) and this problem still exists.

**Comment by Misaka-0x447f** [comment]
Tried to start over and not working. Also, it's really weird that asking me to update helper right after fresh install asked me to install.

**Comment by ActuallyTaylor** [comment]
Hmm, okay on my end everything appears to be alright. This could either be an issue with iCloud or an issue connecting to the server. What region are you in? I can try and VPN myself over there and do some testing

**Comment by Misaka-0x447f** [comment]
China mainland (App store locale: JP, Phone region: TW). It's working now after add "actuallyhome.herokuapp.com" to my proxy list. Maybe you can make the prompt more clear to let user know that it's a network problem, not server problem.

**Comment by TFWol** [comment]
Wait...What?
We're sending our shortcuts to your server?

**Comment by ActuallyTaylor** [comment]
> Wait...What?
> We're sending our shortcuts to your server?
Yep, when Jellycuts was developed, there was no way to sign shortcuts. There are new ways that have been discovered by @0xilis but have yet to be researched. 

As for the signing server, you can see the [privacy policy](https://jellycuts.com/privacy) about how data is handled with it.

**Comment by TFWol** [comment]
Got it. I really didn't see mention of shortcut uploads anywhere obvious because it was sort of hidden like this:
https://github.com/Jellycuts/Jellycuts-Issues/assets/9045213/cf590899-dc73-4a61-a35b-b8dc658b7bef

Fortunately I hadn't built anything since I was in the middle of troubleshooting the vscode bridge.

I'll have to pause things until I can use an alt method or custom server.

**Comment by ActuallyTaylor** [comment]
That view seems to be bugged out, it is usually not a scrollable text view rather an expanding view.

Sorry for the confusion! As for custom servers or methods, check out Open Jellycuts. It will let you sign on your computer directly. It also has open code for how signing is dealt with so you can inspect it or add your own custom server.
