### ISSUE TITLE
Redundant icons for the About button

### ISSUE THREAD

**Issue by FifiTheBulldog** [ActuallyZach/Jellycuts-Issues#28]
## Is your feature request related to a problem? Please describe.
This is a matter of keeping the UI neat. The About button has a heart icon on the left and an info icon on the right. It is the only item with two icons, one of which is redundant.

## Describe the solution you'd like
The heart icon should be removed, and the info icon should be moved to the left where the heart icon is now. The right hand icon spot can be replaced with a disclosure indicator like the rest of the items in Settings have.

## Additional context
![BBEBE524-2797-46D6-AD3F-126A80A9B7C5](https://user-images.githubusercontent.com/63314105/108672843-b7b39d80-74b0-11eb-9c8c-95f430647cd5.jpeg)

**Comment by ActuallyZach** [comment]
This has been fixed for v 0.9(16).
