### ISSUE TITLE
Text editor does not highlight all the code on large files.

### ISSUE THREAD

**Issue by spaceneb** [ActuallyZach/Jellycuts-Issues#29]
<img src="https://cdn.discordapp.com/attachments/755956418619637824/813928038084771910/image0.png">
<img src="https://cdn.discordapp.com/attachments/755956418619637824/813928596140720188/image0.png">

**Comment by ActuallyZach** [comment]
This seems to be an issue with the string length thinking it is what shorter than it really is. I’m still investigating the issue.
