### ISSUE TITLE
Add cancel button to editor theme picker

### ISSUE THREAD

**Issue by FifiTheBulldog** [ActuallyZach/Jellycuts-Issues#34]
## Is your feature request related to a problem? Please describe.
If a user is exploring themes without any intent to actually change it, and doesn't remember exactly which one they had but likes what they've chosen, they have no way to simply exit the theme selector without making any changes to their setup.

## Describe the solution you'd like
Add a Cancel button to the upper left corner of the theme selector.

## Additional context
N/A

**Comment by ActuallyZach** [comment]
Added
