### ISSUE TITLE
After installing the app, the app icon fails to be populated in the app

### ISSUE THREAD

**Issue by FifiTheBulldog** [ActuallyZach/Jellycuts-Issues#35]
## Describe the bug
When I install the app, the default app icon is not populated into the app icon picker or the About page. Nothing is selected in the list of app icons, and the About page has a blank space where the icon should be.

## To Reproduce
1. Install the app.
2. Go to Settings -> Customization -> App Icon and observe that nothing is selected, not even the Default icon
3. Go to Settings -> About and observe that there is no app icon, just a giant space

## Expected behavior
The default app icon should be pre-populated as the chosen icon until the user selects one manually.

### Screenshots
N/A

## Information
 - Device: iPhone SE 2nd generation
 - OS: iOS 14.4.1
 - Jellycuts Version: 0.9(20)

### Additional context
Question: is it possible for the icon selection to persist through app updates?

**Comment by ActuallyZach** [comment]
Fixed in the next update
