### ISSUE TITLE
Make "Default" the default option in "App Tint"

### ISSUE THREAD

**Issue by FifiTheBulldog** [ActuallyZach/Jellycuts-Issues#36]
## Is your feature request related to a problem? Please describe.
"Blue," which is a specific color, is pre-selected as the default app tint. But with the addition of Default and Custom options, blue is obsolete as the default color.

## Describe the solution you'd like
"Default" should be the pre-selected color choice.

## Additional context
I don't do this myself, but for jailbroken users who have customized the default tint system-wide, this would make the experience smoother. Their custom color would show up in Jellycuts without any effort on their part.

**Comment by ActuallyZach** [comment]
Do you know the tweak that customizes this value? That way I can test it out.

**Comment by FifiTheBulldog** [comment]
[Accent](https://moreinfo.thebigboss.org/moreinfo/depiction.php?file=accentDp) works on iOS 14. (Unfortunately I don't have TestFlight on my jailbroken phone.)

**Comment by ActuallyZach** [comment]
Okay I will test test out. Thank you!
