### ISSUE TITLE
Make the toolbar persistent in the editor

### ISSUE THREAD

**Issue by FifiTheBulldog** [ActuallyZach/Jellycuts-Issues#37]
## Is your feature request related to a problem? Please describe.
The toolbar contains a decent amount of utilities, such as the test build button and the undo/redo buttons, and it's frustrating when it disappears and I need it.

## Describe the solution you'd like
The toolbar should follow the keyboard to the bottom edge of the screen but then stay there. It should sit on top of the keyboard when the keyboard is on the screen, and at the bottom edge of the screen when the keyboard is dismissed.

## Additional context
Scriptable has what I think this should look like, though Jellycuts doesn't need to make its toolbar a floating one.

**Comment by ActuallyZach** [comment]
How are you closing the keyboard? It should be staying on the screen.

**Comment by FifiTheBulldog** [comment]
On iPhone, the keyboard stays, but on iPad, I can easily dismiss the keyboard with the button in the lower right corner, and the toolbar disappears.

**Comment by ActuallyZach** [comment]
Oops didn’t mean to close this

**Comment by ActuallyZach** [comment]
I did it again

**Comment by ActuallyZach** [comment]
Okay closing this for real now
