### ISSUE TITLE
"Done" instead of "Dismiss" for modal views

### ISSUE THREAD

**Issue by FifiTheBulldog** [ActuallyZach/Jellycuts-Issues#38]
## Is your feature request related to a problem? Please describe.
It's a bit confusing to me to see "Dismiss" in the upper right hand corner as the button to dismiss modal views. It's inconsistent with other apps.

## Describe the solution you'd like
Change the text of the modal view dismissal button throughout the app from "Dismiss" to "Done."

## Additional context
Pardon me if this sounds like preach Apple interface guidelines, but "Done" is preferable to "Dismiss" because it suggests the user is done with the *content* in the view and puts the focus on the content, rather than dismissing the *view*. The app itself should get out of the way of the content.

**Comment by ActuallyZach** [comment]
Fixed this
