### ISSUE TITLE
Open links in a SFSafariViewController instead of in the Safari app

### ISSUE THREAD

**Issue by FifiTheBulldog** [ActuallyZach/Jellycuts-Issues#48]
## Is your feature request related to a problem? Please describe.
Switching back to the Jellycuts app after tapping on a link is inconvenient.

## Describe the solution you'd like
Links should open a Safari view controller with the built-in option to open the link in Safari, rather than opening Safari itself by default.

## Additional context
I know a lot of other Shortcuts-related apps open links in Safari, but I'm lazy and find it annoying. I'm also the kind of person who hates having new tabs opened because they add up.

**Comment by ActuallyZach** [comment]
Switched over to a SFSafariViewController for the thanks page and anywhere a URL is opened

**Comment by ActuallyZach** [comment]
I also added a customization option to continue opening in the Safari App but it is off by default.
