### ISSUE TITLE
Docs should not have more than one button in the editor

### ISSUE THREAD

**Issue by FifiTheBulldog** [ActuallyZach/Jellycuts-Issues#49]
## Is your feature request related to a problem? Please describe.
The presence of more than one button to get to the docs in the editor is confusing as a new user; it's harder to remember how I accessed them when I'm still learning my way around the app if there are multiple ways to get to the same thing.

## Describe the solution you'd like
Remove either the button in the toolbox or the button in the toolbar. The convenience of the docs being right there in the toolbar leads me to say that the docs should be removed from the toolbox.

## Additional context
N/A

**Comment by ActuallyZach** [comment]
Removed the doc button in tools
