### ISSUE TITLE
Terminal enhancements

### ISSUE THREAD

**Issue by FifiTheBulldog** [ActuallyZach/Jellycuts-Issues#50]
## Is your feature request related to a problem? Please describe.
The text in the "Terminal" is too small to be easily legible

Its name is confusing--when I think of a terminal, I think of an interactive command line or similar interface, not a console where things are logged and nothing more.

It's a bit confusing to pull up on the top as the interface implies and have the whole toolbar come up to reveal the console below.

## Describe the solution you'd like
Increase the font size in the console,

Rename the console to "console" throughout the app.

Place the console on top of the suggestions and the buttons in the toolbar, so that those don't move when the console opens.

## Additional context
Maybe consider adding a title bar like "Console" or something to the terminal so that it's clearer exactly what I'm looking at?

**Comment by ActuallyZach** [comment]
Animations are hard but I finally got this to work 👍. Thank you, it looks way better now.
