### ISSUE TITLE
Toolbar contents crammed to the left after opening and closing a new documentation window on iPad

### ISSUE THREAD

**Issue by FifiTheBulldog** [ActuallyZach/Jellycuts-Issues#61]
## Describe the bug
When I'm editing a jellycut on my iPad, and I've opened the documentation in a new window and then dismissed it, the contents of the toolbar are crammed into the horizontal space that the sidebar would usually cover, rather than being spread out across the screen like they usually are.

When in portrait mode, the toolbar contents are crammed into the horizontal space that the sidebar would usually cover. In landscape mode, the toolbar contents are stuck in the horizontal space that the editor window occupied while the docs were open.

## To Reproduce
1. Open up a jellycut in the editor.
2. Open the documentation from the toolbar.
3. Tap the macwindow.badge.plus button in the upper left corner to open the docs in a new window.
4. Tap "Dismiss" on the documentation window.
5. Observe that the toolbar contents are crammed to the area that the sidebar would usually cover.

## Expected behavior
The toolbar contents should fill the width of the screen at all times while the toolbar is visible.

### Screenshots
![IMG_0323](https://user-images.githubusercontent.com/63314105/111581497-b9127600-878f-11eb-81ef-42df369da9f5.PNG)

## Information
 - Device: iPad (7th generation)
 - OS: iPadOS 14.4.1
 - Jellycuts Version: 0.9(20)

### Additional context
You said on the Discord server that you've encountered this as well in your own tests; I'm just leaving this here as an issue for the bug tracker.

**Comment by FifiTheBulldog** [comment]
I just found out how to reproduce the bug! I've updated my the issue with the method. Hopefully this helps get to the bottom of the problem.

**Comment by ActuallyZach** [comment]
This should be solved in the new update.
