### ISSUE TITLE
Repeat Item variable not found in scope

### ISSUE THREAD

**Issue by FifiTheBulldog** [ActuallyZach/Jellycuts-Issues#67]
## Describe the bug
When using the Repeat Item variable inside a repeatEach loop, there is a "not found in scope" error.

## To Reproduce
1. Create a Jellycut that uses repeatEach and uses the Repeat Item variable within the repeatEach loop.
2. Try to compile or export the jellycut.
3. Open the console to see the "not found in scope" error.

## Expected behavior
The jellycut should compile normally, rather than erroring out.

### Screenshots
![IMG_8454](https://user-images.githubusercontent.com/63314105/112324760-81249a80-8c89-11eb-9d4d-5ce49204e5ea.PNG)
![IMG_8455](https://user-images.githubusercontent.com/63314105/112324775-841f8b00-8c89-11eb-8bae-2af2bf36732d.PNG)

## Information
 - Device: iPhone SE (2nd generation)
 - OS: iOS 14.4.1
 - Jellycuts Version: 0.9(20)

### Additional context
Jelly code to test:

```
repeatEach(Clipboard) {
	quicklook(input: Repeat Item)
}
```

**Comment by ActuallyZach** [comment]
Fixed in 0.9(24)
