### ISSUE TITLE
Random crashes when scrolling in settings

### ISSUE THREAD

**Issue by FifiTheBulldog** [ActuallyZach/Jellycuts-Issues#69]
## Describe the bug
Scrolling up and down through the settings a few times causes the app to crash.

## To Reproduce
1. Launch the app.
2. Go to the settings page.
3. Scroll to the bottom, then back to the top, then repeat this over and over until the view freezes and the app crashes.

## Expected behavior
Scrolling through a static page of items should not crash the app, no matter how much I scroll.

### Screenshots
N/A

## Information
 - Device: iPhone SE (2nd generation)
 - OS: iOS 14.4.2
 - Jellycuts Version : 0.9(29)

### Additional context
This may have something to do with some of the disclosure indicators being replaced with globe symbols. This bug never occurred when all items had either arrows as disclosure indicators or no disclosure indicators at all.

**Comment by ActuallyZach** [comment]
How long do you have to scroll for this to happen?  I can’t seem to replicate the globe or the settings bug.

**Comment by colin273** [comment]
https://user-images.githubusercontent.com/63314105/114425569-3363c980-9b87-11eb-86fd-60b62cfcef29.mov

**Comment by ActuallyTaylor** [comment]
That is beyond strange. I managed to get crashing, to happen and it seems to be an issue with a memory leak. Why a memory leak is caused by my settings page I have 0 clue. This ones gonna be annoying to squash.

**Comment by ActuallyTaylor** [comment]
This one was hard to find and I have no clue why the code that I changed fixed it but it did.
