### ISSUE TITLE
Scrolling changes the symbol to the right of the "Jellycuts Pro"/"Tip Jar" button in settings

### ISSUE THREAD

**Issue by FifiTheBulldog** [ActuallyZach/Jellycuts-Issues#70]
## To Reproduce
1. Go to the settings page
2. Scroll down so that "Jellycuts Pro" (or "Tip Jar") is no longer visible on the screen
3. Scroll back up so that the aforementioned item is visible again.
4. See that the disclosure indicator has been changed to a globe symbol.

## Expected behavior
The icons for each item should remain constant when navigating.

### Screenshots
![IMG_8576](https://user-images.githubusercontent.com/63314105/114351492-b0b41d80-9b38-11eb-84b6-f50f6df45649.PNG)
![IMG_8577](https://user-images.githubusercontent.com/63314105/114351493-b14cb400-9b38-11eb-9cd0-58597dde750a.PNG)

## Information
 - Device: iPhone SE (2nd generation)
 - OS: iOS 14.4.2
 - Jellycuts Version: 0.9(29)

### Additional context
N/A

**Comment by ActuallyTaylor** [comment]
The fix in #69 should also fix this.
