### ISSUE TITLE
Add cancel button to Jellycuts Pro purchase screen

### ISSUE THREAD

**Issue by FifiTheBulldog** [ActuallyZach/Jellycuts-Issues#71]
## Is your feature request related to a problem? Please describe.
This has been addressed before for other modal views in the app, but there should be a Cancel and/or Done button on the purchase screen for Jellycuts Pro. Otherwise the only way to dismiss the view is to swipe down, which may not be immediately obvious and can be more difficult for some users.

## Describe the solution you'd like
Add a cancel button or a done button (or both, whatever would be best) to the purchase screen.

## Additional context
N/A

**Comment by JdenHartog** [comment]
Agreed, I was also trapped in the purchase screen for A long time 😃
