### ISSUE TITLE
Add linefeeds when converting *Run Javascript on Webpage* action

### ISSUE THREAD

**Issue by JdenHartog** [ActuallyZach/Jellycuts-Issues#72]
## Is your feature request related to a problem? Please describe.
As mentioned [here](https://github.com/ActuallyZach/Jellycuts-Issues/issues/68#issuecomment-814382962) all JavaScript ends up in one line when converting a Jellycut to a Shortcut when using the *Run Javascript on Webpage* action.

## Describe the solution you'd like
So a solution could be adding a linefeed after every `;` sign, when converting te JellyCut into a shortcut, so each JavaScript statement gets its own line.

**Comment by ActuallyTaylor** [comment]
I like the idea, I think it will need to be an option for the user to toggle however.
