### ISSUE TITLE
Nitpicks

### ISSUE THREAD

**Issue by ghost** [ActuallyZach/Jellycuts-Issues#74]
## Nitpicks
Not real bugs but just things that would make the experience more Apple-like.

- Apple won't like you called the hammer a play icon, also I think you should just do a zoomed in screenshot. 

![](https://media.discordapp.net/attachments/746030320905617568/842215963687911444/image0.png)

- This should be called the share arrow

![](https://media.discordapp.net/attachments/746030320905617568/842216007660732429/image0.png)

- Fix the period

![](https://media.discordapp.net/attachments/746030320905617568/842216654631862293/image0.png)

- This is slow
https://media.discordapp.net/attachments/746030320905617568/842216691367018527/video0.mp4

- Make sure the descriptions are formatted in the same way

![](https://media.discordapp.net/attachments/746030320905617568/842217204266565662/image0.png)

![](https://media.discordapp.net/attachments/746030320905617568/842217204538802176/image1.png)

- Make sure links are consistent & remove resident links

![](https://media.discordapp.net/attachments/746030320905617568/842217769038774292/image0.png)

![](https://media.discordapp.net/attachments/746030320905617568/842217860427939850/image0.png)

![](https://media.discordapp.net/attachments/746030320905617568/842218001549361202/image0.png)

## Information
 - Device: iPhone 7+
 - OS: 14.3
 - Jellycuts Version 0.9(29)
 - Jailbroken? Yes

**Comment by ghost** [comment]
Please fix `Make sure the descriptions are formatted in the same way`

**Comment by ActuallyTaylor** [comment]
Yep I have gone through and fixed the ones I could find.
