### ISSUE TITLE
Music quits playing when app is opened

### ISSUE THREAD

**Issue by EggsistentialBread** [ActuallyZach/Jellycuts-Issues#79]
## Describe the bug
Music playing from SoundCloud fades out when JellyCuts is opened.

## Expected behavior
I expected my music to continue playing while I coded.

## Information
 - Device: iPhone 7
 - OS: iOS 14.5.1
 - Jellycuts Version v1.0(3)
 - Jailbroken? No

### Additional context
This might just be an issue with SoundCloud, I’m not sure if the same would happen with Apple Music or other music streaming platforms.

**Comment by ActuallyTaylor** [comment]
Why was this closed?

**Comment by EggsistentialBread** [comment]
Sorry I am completely new to GitHub and on mobile so I prematurely submitted the issue, should I try again?

**Comment by ActuallyTaylor** [comment]
You're all good. You can edit this issue if you would like and I can reopen it for you. That way you don’t have to write another issue out.

**Comment by EggsistentialBread** [comment]
Okie dokie! Thanks!

**Comment by ActuallyTaylor** [comment]
I can’t seem to reproduce this with soundcloud. Are there any settings you have set in sound cloud that change the way audio is played?

**Comment by EggsistentialBread** [comment]
I’m not really sure what happened, because it’s working completely fine for me now too.  I will mention that the same thing has happened with some of my other apps since then so it must be an issue with my device.  Thanks for looking into this though, sorry for the trouble!

**Comment by ActuallyTaylor** [comment]
Good to know this happens on a bunch of different apps. I will keep my eye out for a solution to it. And you didn’t cause any trouble, thank you for reporting this!
