### ISSUE TITLE
formatDate from imported shortcut doesn’t actually contain the format to be used

### ISSUE THREAD

**Issue by scottaw66** [ActuallyZach/Jellycuts-Issues#88]
Done## Describe the bug
After importing a shortcut, I noticed that the three date formatters at the top of the shortcut don’t actually have any format applied… ie, the format itself doesn’t appear to have been imported.

## Expected behavior
I expected the date formatting to have been applied

### Screenshots
![IMG_1692](https://user-images.githubusercontent.com/7348442/118731046-64ba5f80-b7ed-11eb-8822-8373082f9dc3.jpeg)

![IMG_1693](https://user-images.githubusercontent.com/7348442/118731014-5c622480-b7ed-11eb-8df3-a521c0696ae1.jpeg)

## Information
 - Device: [iPad Pro 12.9”]
 - OS: [iPadOS 14.5.1]
 - Jellycuts Version [1.0(3)]
 - Jailbroken? [No]

**Comment by ActuallyTaylor** [comment]
Thank you for submitting this onto GitHub, I will be looking into fixing a lot of the bugs that are present in the current converter. However, a lot of the issues with data missing is because Shortcuts does not actually save this data to the .shortcut file that I have the ability to access.

**Comment by ActuallyTaylor** [comment]
Can you please supply an iCloud url for the original shortcut?

**Comment by scottaw66** [comment]
Mind if I send it to you privately?

**Comment by ActuallyTaylor** [comment]
Yep that works, you can either DM me on Twitter or through discord. Whichever works for you.

**Comment by ActuallyTaylor** [comment]
This should be fixed in the most recent version.
