### ISSUE TITLE
Default shortcut name includes .shortcut which actually gets added to the shortcut name in Shortcuts

### ISSUE THREAD

**Issue by scottaw66** [ActuallyZach/Jellycuts-Issues#89]
## Describe the bug
Jellycuts exports the jellycut shortcut with the name shortcutname.shortcut, but Shortcuts interprets this literally and adds “.shortcut” as part of the shortcut name.

## To Reproduce
1. Export a shortcut from Jellycuts
2. Tap the “Add untrusted shortcut” button
3. Look at the title

## Expected behavior
The name of the shortcut should just be the name given in Jellycuts, without “.shortcut” appended as part of the name

### Screenshots
![7C71E4DA-3921-45EA-9B13-307BCC18C03D](https://user-images.githubusercontent.com/7348442/118745203-8aa22d00-b80a-11eb-9d4c-8278b7f529e6.jpeg)
![660FC2ED-8D82-496A-9698-F413ADA34BFE](https://user-images.githubusercontent.com/7348442/118745207-8d048700-b80a-11eb-866d-4bb61334f817.jpeg)

## Information
 - Device: [iPad Pro 12.9” 2020]
 - OS: [iPadOS 14.5.1]
 - Jellycuts Version [1.0(3)]
 - Jailbroken? [No]

**Comment by ActuallyTaylor** [comment]
This is an issue on the end of Shortcuts. I have confirmed this by reaching out to the developers. To the best of my knowledge they have submitted a fix but there is no timeline on when this will be excepted or if it was even submitted.

Hopefully this is fixed soon as it is a little nagging thing in the app. 🤞for iOS 15 to fix this issue.
