### ISSUE TITLE
Filter condition value does not populated when using filterReminders

### ISSUE THREAD

**Issue by warthurton** [ActuallyZach/Jellycuts-Issues#91]
# What action is the issue?
filterReminders

## Describe the bug
Filter condition value does not populated.  i.e. the string being searched for.

## Steps To Reproduce
```
import Shortcuts 1092.6
#Color: red, #Icon: shortcuts

filterReminders(input: All Reminders, filterType: All, filter: {Name: == : Test}, sortBy: Creation Date, order: Oldest First, limit: 20)
```

### Screenshots
![image](https://user-images.githubusercontent.com/202251/118852434-cab3ef00-b8a0-11eb-82e6-9584c31cf803.png)

## Information
Device: iPhone 11 Pro
OS: iOS 14.5.1
Jullycuts v1.0(3)
Jailbroken? No

**Comment by ActuallyTaylor** [comment]
This has been fixed for the next version.
