### ISSUE TITLE
Documentation is out of date for magic variables

### ISSUE THREAD

**Issue by gruber** [ActuallyZach/Jellycuts-Issues#93]
Jellycuts v1.1(8)

The documentation for magic variable assignment syntax is out of date in Learning Center → The Basics.

The docs show the `function() -> [variable name]` syntax, but the changelog for the Jelly 2.2.1 language says that syntax is deprecated, replaced by `function() >> variable name`.

**Comment by ActuallyTaylor** [comment]
Thank you for letting me know 👍, this will be fixed in the 1.1.1 update!
