### ISSUE TITLE
Magic variables with the same name after import

### ISSUE THREAD

**Issue by atnbueno** [ActuallyZach/Jellycuts-Issues#94]
When importing a shortcut, the output of each action/function is assigned to a magic variable named after the function. If the same action/function is used more than once in the shortcut, the compiler will complaint about **repeated names** ("text", "text", "text", ...).

The easiest solution I can think is to **add a number at the end** of the magic variable name ("text1", "text2", "text3", ...).

Ideally we would get the original name of each action output ("Contents of Web Page" instead of "urlContents"), but that is locale-dependant ("Text", "Texto", "Texte", ...).

**Comment by atnbueno** [comment]
An additional detail: Shortcuts allows magic variables with the same name, but that's a significant source of mistakes, especially if you copy and paste or duplicate actions. I'm all in favor of not allowing them.

**Comment by ghost** [comment]
The optimal and easiest solution in my opinion, would just be to grab the UUIDs and use those as names, but this wouldn't be very readable. Another nice option would be to refactor and change all instances of `x` to `y`

**Comment by ActuallyTaylor** [comment]
Fixed for version 1.4. Magic variables will now increase sequentially
