### ISSUE TITLE
runSSH function does not get converted into an action

### ISSUE THREAD

**Issue by alven-shin** [ActuallyZach/Jellycuts-Issues#95]
# What action is the issue?
runSSH

## Describe the bug
Using the example runSSH or my own function does not make an action when converting to a shortcut.

## Steps To Reproduce
1. copy and paste code
2. convert to shortcut
```
import Shortcuts 1092.6
#Color: red, #Icon: shortcuts
runSSH(host: "pi_address", port: "22", user: "raspberry", auth: password, password: "••••••••", script: Shortcut Input)
```

## Information
 - Device: iPhone 8 Plus (jailbroken)
 - OS: ios 14.3
 - Jellycuts Version: 1.1.1(3)

**Comment by ActuallyTaylor** [comment]
Okay this is fixed in 1.1.2, which should be releasing soon 👍
