### ISSUE TITLE
Adding to a variable creates an extra set variable action

### ISSUE THREAD

**Issue by alven-shin** [ActuallyZach/Jellycuts-Issues#97]
# What action is the issue?
var

## Describe the bug
When using the += operator to add to a variable, a redundant set variable action is created above the add to variable action which causing an error when running the shortcut if it isn't deleted.

## Steps To Reproduce
Create jellycut with the follow code:
```
import Shortcuts 1092.6
#Color: red, #Icon: shortcuts

text(text: "text") >> hello
var text = hello
text(text: "world") >> world
var text += world
```

### Screenshots
![image0](https://user-images.githubusercontent.com/29553973/125125030-08760c80-e0c7-11eb-8653-f0231482619a.png)

## Information
 - Device: iPhone 8 Plus
 - OS: iOS 14.3 (jailbroken)
 - Jellycuts Version 1.1.3(2)

**Comment by ActuallyTaylor** [comment]
Thank you for reporting this!  This will be fixed in the next version of the app.
